# This file a conversion of the swagger.yaml file and was expanded with semantic descriptors
openapi: 3.0.1
info:
  title: spaghetti-back-end
  version: 0.0.4
servers:
- url: http://localhost:10010/
- url: https://localhost:10010/
paths:
  /analyzeText/:
    post:
      description: Get analysis data and feedback for given text
      operationId: analyzeEntry
      x-@id: evolvable:analyze
      requestBody:
        description: the data containing the text and username + password if applicable
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/analyzeEntry'
        required: true
      responses:
        200:
          description: Text analysis success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/entryAnalysis'
        400:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /createUser/{userName}/password/{password}:
    put:
      description: Create a new user, optionally setting their historyData ifsome has already been generated
      operationId: createUser
      x-@id: evolvable:createUser
      parameters:
      - name: userName
        x-@id: evolvable:userName
        in: path
        description: The desired username
        required: true
        schema:
          type: string
      - name: password
        x-@id: evolvable:password
        in: path
        description: The desired password
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                historyData:
                  description: A list of history data that the user has already generated before they signed up
                  x-@id: evolvable:history
                  type: object
      responses:
        201:
          description: User creation success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericResponse'
        400:
          description: User name already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /retrieveUser/{userName}/password/{password}:
    get:
      description: Retrieve an existing user
      operationId: retrieveUser
      x-@id: evolvable:findUser
      parameters:
      - name: userName
        x-@id: evolvable:userName
        in: path
        description: The existing username
        required: true
        schema:
          type: string
      - name: password
        x-@id: evolvable:password
        in: path
        description: The existing password
        required: true
        schema:
          type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericResponse'
        400:
          description: User name does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        401:
          description: Password incorrect
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /updateUser/{userName}/password/{password}:
    post:
      description: Takes a JSON object in the request body, and adds it to thefront
        of the 'entryList' field. Currently accepts any valid JSON object.
      operationId: updateUser
      x-@id: evolvable:updateUser
      parameters:
      - name: userName
        x-@id: evolvable:userName
        in: path
        description: The needed username
        required: true
        schema:
          type: string
      - name: password
        x-@id: evolvable:password
        in: path
        description: The needed password
        required: true
        schema:
          type: string
      requestBody:
        description: Entry to be added
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        201:
          description: User updated successfully!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericResponse'
        404:
          description: User not found!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /deleteEntry/{userName}/password/{password}/entryIndex/{entryIndex}:
    delete:
      description: Deletes a user entry at given array index
      operationId: deleteEntry
      x-@id: evolvable:deleteEntry
      parameters:
      - name: userName
        x-@id: evolvable:userName
        in: path
        description: The needed username
        required: true
        schema:
          type: string
      - name: password
        x-@id: evolvable:password
        in: path
        description: The needed password
        required: true
        schema:
          type: string
      - name: entryIndex
        x-@id: evolvable:entryIndex
        in: path
        description: Array index of the entry to be deleted
        required: true
        schema:
          type: integer
      responses:
        200:
          description: The entry at index was deleted successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericResponse'
        404:
          description: User not found!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    genericResponse:
      required:
      - message
      type: object
      properties:
        message:
          type: string
          x-@id: schema:description
    ErrorResponse:
      required:
      - message
      type: object
      properties:
        message:
          type: string
          x-@id: schema:description
    analyzeEntry:
      required:
      - text
      type: object
      properties:
        text:
          x-@id: evolvable:textToAnalyze
          type: string
        username:
          x-@id: evolvable:userName
          type: string
        password:
          x-@id: evolvable:password
          type: string
    entryAnalysis:
      required:
      - data
      - message
      type: object
      properties:
        message:
          x-@id: schema:description
          type: string
        data:
          type: object
          x-affiliation: parent
          properties:
            date:
              type: string
              x-@id: evolvable:analysisDate
            entry:
              type: string
              x-@id: evolvable:analysisEntry
            sentimentData:
              type: object
              x-@id: evolvable:sentiment
              properties:
                feelingScore:
                  type: integer
                  x-@id: evolvable:feelingScore
                feedback:
                  type: string
                  x-@id: evolvable:analysisFeedback
            classificationData:
              type: string
              x-@id: evolvable:classification
# json-LD context
x-@context:
  x-@context: '@context'
  x-@id: '@id'
  x-@type: '@type'
  x-@relation: 'dce:relation'
  schema: 'http://schema.org/'
  evolvable: 'https://github.com/evolvable-by-design/use-cases/spaghetti-makes-me-moody/vocab#'